server:
  port: 8000

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    liquibase-schema: liquibase
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 5s

model:
  regularization-parameter: 0.01
  factors: 32
  offline-iterations: 5
  online-iterations: 1
  latent-init-mean: 0
  latent-init-deviation: 0.01
  popularity-significance: 0.4
  new-item-weight: 0.5
  thread-number: 1
  top-k: 10

  initializer:
    source: DATABASE
    train: false
    user-interaction-threshold: 0
    load-item-count: 10000
    shrink-users: true
    tables:
      user-interaction: user_item
      user-vector: user_vectors
      item-vector: item_vectors
    save-after-build: true
    save-after-update: true

kafka:
  topic:
    event-topic: recommendation-event
  consumer:
    group-id: recommendation-service-group
    client-id: recommendation-client
    bootstrap-server: localhost:9092
    commit-interval: 5
    poll-interval: 10
    session-timeout: 30000